# General simulation settings
# variables:
#   &user_timesteps 18400

general:
  USER_TIMESTEPS: 25200       # Number of user timesteps
  DATA_SOURCE: "scenario_sumo"
  SNIFFER_DATA_SOURCE: "scenario_synced_randomization_512_all"
  MAPPING_SOURCE: "scenario_synced_randomization_512_all"
  IDENTIFIER_LENGTH: 8
  ID_RANDOMIZATION: exponential

user_threshold:
  TOTAL_NUMBER_OF_USERS: 512          # Create only same set of users for different run

# Randomization Intervals
randomization_intervals:
  ENABLE_SYNCED_RANDOMIZATION: true
  PROTOCOL_MIN_REFRESH: 600

#Transmission Intervals
transmission_intervals:
  # Bluetooth IDs transmit range uniform (in seconds)
  BLUETOOTH_MIN_TRANSMIT: 0
  BLUETOOTH_MAX_TRANSMIT: 60

  # WiFi ID transmit range uniform (in seconds)
  WIFI_MIN_TRANSMIT: 0
  WIFI_MAX_TRANSMIT: 60

  # LTE transmit range uniform (in seconds)
  LTE_MIN_TRANSMIT: 0
  LTE_MAX_TRANSMIT: 60

# Range for communication protocols
communication_range:
  BLUETOOTH_RANGE: 30                # Bluetooth range (in meters)
  WIFI_RANGE: 60                     # WiFi range (in meters)
  LTE_RANGE: 100                     # LTE range (in meters)

# Localization errors
localization_errors:
  BLUETOOTH_LOCALIZATION_ERROR: 1    # Bluetooth localization error (in meters)
  WIFI_LOCALIZATION_ERROR: 5         # WiFi localization error (in meters)
  LTE_LOCALIZATION_ERROR: 10         # LTE localization error (in meters)

smart:
  ENABLE_SMART_TRACKING: true

# Mobility settings
mobility:
  MAX_MOBILITY_FACTOR: 1.5       # Mobility factor in m/s
# Sniffer settings
sniffer:
  GENERATE_SNIFFER_DATA: false
  ENABLE_PARTIAL_COVERAGE: false
  ENABLE_MULTILATERATION: false
  ENABLE_BLUETOOTH: true       # Enable Bluetooth
  ENABLE_WIFI: true            # Enable Bluetooth
  ENABLE_LTE: false             # Enable Bluetooth
  TRANSMIT_WHEN_RANDOMIZED: false
  SNIFFER_PROCESSING_BATCH_SIZE: 1000 # Sniffer processing batch size
